set(_CATKIN_CURRENT_PACKAGE "joystick")
set(joystick_VERSION "0.0.0")
set(joystick_MAINTAINER "magnus <magnus@todo.todo>")
set(joystick_PACKAGE_FORMAT "2")
set(joystick_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(joystick_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(joystick_BUILDTOOL_DEPENDS "catkin")
set(joystick_BUILDTOOL_EXPORT_DEPENDS )
set(joystick_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(joystick_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(joystick_TEST_DEPENDS )
set(joystick_DOC_DEPENDS )
set(joystick_URL_WEBSITE "")
set(joystick_URL_BUGTRACKER "")
set(joystick_URL_REPOSITORY "")
set(joystick_DEPRECATED "")